chat-filter:
  enabled: true
  blocked-words:
    - Чурка
    - Чурки
    - Чурок
    - Блядота
    - Блядина
    - Симп
    - Пидорас
    - Пидорасы
    - Педики
    - Педик
    - Хуесос
    - Пиздализ
    - Уебан
    - Гандон
    - Гандоны
    - Докс
    - Жид
  cancel-message: "<red>Ваше сообщение было заблокировано!"
